export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCESS = "GET_PRODUCT_SUCESS";

export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";

export const GET_BREADCRUM = "GET_BREADCRUM";
export const GET_BREADCRUM_SUCCESS = "GET_BREADCRUM_SUCCESS";

export const SORT_SUCCESS = "SORT_SUCCESS"

export const PAGINATION_SUCCESS = "PAGINATION_SUCCESS";

export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_SUCESS = "FETCH_CATEGORY_SUCESS";

export const LOADING_QUERY = "LOADING_QUERY";

export const SORT_DEFAULT = "SORT_DEFAULT"