export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCESS = "GET_PRODUCT_SUCESS";

export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";