export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const ADD_CART_IN_DATABASE = "ADD_CART_IN_DATABASE";
export const ADD_CART_IN_DATABASE_SUCCESS = "ADD_CART_IN_DATABASE_SUCCESS";